# Generated by Django 3.2.5 on 2022-01-17 08:13

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathology', '0010_auto_20211202_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathologypictureitem',
            options={'verbose_name': '肝穿图片', 'verbose_name_plural': '肝穿图片集'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bodySource',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deadReason',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deathDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lastModifiedAt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operateDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operateDiagose',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operateRecord',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operateSeqNumber',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='otherDoctors',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='otherDocument',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photoNum',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pptNum',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pptRecord',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sliceNum',
        ),
        migrations.AddField(
            model_name='patient',
            name='admissionNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住院号'),
        ),
        migrations.AddField(
            model_name='patient',
            name='advice',
            field=models.TextField(default=0, verbose_name='意见'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='bedNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='病床'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='送检医院'),
        ),
        migrations.AddField(
            model_name='patient',
            name='microscopy',
            field=models.TextField(default=0, verbose_name='镜检'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='receiveDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='收到日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='roomNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='病房'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sampleNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标本号'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='bigPathologyPicture',
            field=models.FileField(blank=True, help_text='size >= 1G的图片或无法正常显示的图片', null=True, upload_to='images', verbose_name='大肝穿图片'),
        ),
        migrations.AlterField(
            model_name='pathologypictureitem',
            name='pathologyPicture',
            field=models.ImageField(blank=True, help_text='size < 1G的图片', null=True, upload_to='images', verbose_name='肝穿图片'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='_pathology_patient_doctors_+', to=settings.AUTH_USER_MODEL, verbose_name='诊断医生'),
        ),
    ]
